/**
 * 初始化装饰物定义数据
 * 从 add-decorations.ts 中的配置导入到数据库
 */

import { db } from '../app/db';
import { decorationDefinitions } from '../src/db/schema';

async function initDecorationDefinitions() {
  console.log('🎨 开始初始化装饰物定义...\n');

  const definitions = [
    // ========================================
    // 室内装饰物 (indoor)
    // ========================================
    {
      name: '宝箱',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/chest01.png',
      size: 1,
      blocking: true,
      interactable: true,
      pickable: true,
      description: '可以打开的宝箱，可能包含珍贵物品',
    },
    {
      name: '宝箱',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/chest02.png',
      size: 1,
      blocking: true,
      interactable: true,
      pickable: true,
      description: '可以打开的宝箱，可能包含珍贵物品',
    },
    {
      name: '箱子',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/boxes01.png',
      size: 1,
      blocking: true,
      interactable: true,
      description: '普通的储物箱',
    },
    {
      name: '箱子',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/boxes02.png',
      size: 1,
      blocking: true,
      interactable: true,
      description: '普通的储物箱',
    },
    {
      name: '蘑菇',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/mushroom01.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
      description: '可食用的蘑菇',
    },
    {
      name: '蘑菇',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/mushroom02.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
      description: '可食用的蘑菇',
    },
    {
      name: '岩石',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/rocks01.png',
      size: 1,
      blocking: true,
      interactable: false,
      description: '普通的岩石',
    },
    {
      name: '岩石',
      type: 'decoration',
      category: 'indoor',
      imagePath: '/game/isometric/items/rocks02.png',
      size: 1,
      blocking: true,
      interactable: false,
      description: '普通的岩石',
    },

    // ========================================
    // 户外装饰物 (outdoor)
    // ========================================
    {
      name: '马车',
      type: 'decoration',
      category: 'outdoor',
      imagePath: '/game/isometric/items/carriage01.png',
      size: 2,
      blocking: true,
      interactable: true,
      description: '装载货物的马车',
    },
    {
      name: '岩石',
      type: 'decoration',
      category: 'outdoor',
      imagePath: '/game/isometric/items/rocks03.png',
      size: 1,
      blocking: true,
      interactable: false,
      description: '户外的大石头',
    },
    {
      name: '岩石',
      type: 'decoration',
      category: 'outdoor',
      imagePath: '/game/isometric/items/rocks04.png',
      size: 1,
      blocking: true,
      interactable: false,
      description: '户外的大石头',
    },
    {
      name: '岩石',
      type: 'decoration',
      category: 'outdoor',
      imagePath: '/game/isometric/items/rocks05.png',
      size: 1,
      blocking: true,
      interactable: false,
      description: '户外的大石头',
    },
    {
      name: '蘑菇',
      type: 'decoration',
      category: 'outdoor',
      imagePath: '/game/isometric/items/mushroom03.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
      description: '野生蘑菇',
    },
    {
      name: '蘑菇',
      type: 'decoration',
      category: 'outdoor',
      imagePath: '/game/isometric/items/mushroom04.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
      description: '野生蘑菇',
    },

    // ========================================
    // 植物 (plants)
    // ========================================
    {
      name: '竹子',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bamboo01.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
      description: '可以制作棋盘的竹子',
    },
    {
      name: '竹子',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bamboo02.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
      description: '可以制作棋盘的竹子',
    },
    {
      name: '竹子',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bamboo03.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
      description: '可以制作棋盘的竹子',
    },
    {
      name: '竹子',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bamboo04.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
      description: '可以制作棋盘的竹子',
    },
    {
      name: '大树',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bigtree01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
      description: '可以制作棋盘和棋子的大树',
    },
    {
      name: '大树',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bigtree02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
      description: '可以制作棋盘和棋子的大树',
    },
    {
      name: '灌木',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bush01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '灌木',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bush02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '灌木',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bush03.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '灌木',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/bush04.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '草丛',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/grasses01.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '草丛',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/grasses02.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '草丛',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/grasses03.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '草丛',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/grasses04.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '棕榈树',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/palm01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
      description: '热带植物，可以制作棋盘和棋子',
    },
    {
      name: '棕榈树',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/palm02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
      description: '热带植物，可以制作棋盘和棋子',
    },
    {
      name: '松树',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/pine-full01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
      description: '可以制作棋盘和棋子的松树',
    },
    {
      name: '松树',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/pine-full02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
      description: '可以制作棋盘和棋子的松树',
    },
    {
      name: '灌木丛',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/shrub1-01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '盆栽',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/shrub1-02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: false,
      description: '室内装饰植物',
    },
    {
      name: '灌木丛',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/shrub2-01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的草药',
    },
    {
      name: '盆栽',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/shrub2-02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: false,
      description: '室内装饰植物',
    },
    {
      name: '热带植物',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/tropical01.png',
      size: 2,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的热带药草',
    },
    {
      name: '热带植物',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/tropical02.png',
      size: 2,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的热带药草',
    },
    {
      name: '野草',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/weed01.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的野草',
    },
    {
      name: '野草',
      type: 'plant',
      category: 'plants',
      imagePath: '/game/isometric/plants/weed02.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
      description: '可以制药的野草',
    },

    // ========================================
    // 西式建筑 (buildings)
    // ========================================
    {
      name: '教堂',
      type: 'building',
      category: 'buildings',
      imagePath: '/game/isometric/buildings/church/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '大型教堂建筑，可进入触发剧情',
    },
    {
      name: '兵营',
      type: 'building',
      category: 'buildings',
      imagePath: '/game/isometric/buildings/barracks/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '军队营地，可进入触发剧情',
    },
    {
      name: '消防站',
      type: 'building',
      category: 'buildings',
      imagePath: '/game/isometric/buildings/firestation/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '消防站建筑，可进入触发剧情',
    },
    {
      name: '草药铺',
      type: 'building',
      category: 'buildings',
      imagePath: '/game/isometric/buildings/herbary/renders/idle/45/000.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '草药店铺，可以购买药材和炼药',
    },
    {
      name: '武器铺',
      type: 'building',
      category: 'buildings',
      imagePath: '/game/isometric/buildings/weaponsmith/renders/idle/45/000.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '武器店铺，可以购买和强化武器',
    },

    // ========================================
    // 中式建筑 (chinese_buildings)
    // ========================================
    {
      name: '二层楼',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/2stories.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '中式二层楼阁，可进入触发剧情',
    },
    {
      name: '祭坛',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/altar.png',
      size: 2,
      blocking: true,
      interactable: true,
      enterable: false,
      description: '祭祀用的祭坛，可以祈福',
    },
    {
      name: '建筑',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/building.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '普通建筑，可进入触发剧情',
    },
    {
      name: '马',
      type: 'decoration',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/horse.png',
      size: 2,
      blocking: true,
      interactable: true,
      description: '栓着的马匹，可以互动',
    },
    {
      name: '房屋',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/house.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '普通民居，可进入触发剧情',
    },
    {
      name: '工坊',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/mechanic.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '工匠作坊，可以制作物品',
    },
    {
      name: '老房子',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/old_house.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '古老的房屋，可进入触发剧情',
    },
    {
      name: '宫殿',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/palace.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '宏伟的宫殿建筑，可进入触发剧情',
    },
    {
      name: '平台',
      type: 'decoration',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/platform.png',
      size: 2,
      blocking: true,
      interactable: false,
      description: '石制平台',
    },
    {
      name: '商铺',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/shop.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '商铺，可以购买物品',
    },
    {
      name: '店铺1',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/shop1.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '店铺，可以购买物品',
    },
    {
      name: '店铺2',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/shop2.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '店铺，可以购买物品',
    },
    {
      name: '庭院',
      type: 'building',
      category: 'chinese_buildings',
      imagePath: '/game/isometric/chinese_buildings/yard.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
      description: '庭院建筑，可进入触发剧情',
    },

    // ========================================
    // 动画装饰物 (animated)
    // ========================================
    {
      name: '信号火',
      type: 'decoration',
      category: 'animated',
      imagePath: '/game/isometric/buildings/signal_fire/renders/work/45/000.png',
      size: 2,
      blocking: true,
      interactable: false,
      animated: true,
      animationPath: '/game/isometric/buildings/signal_fire/renders/work/45',
      frameCount: 16,
      description: '燃烧的信号火',
    },
  ];

  // 批量插入
  let insertCount = 0;
  let skipCount = 0;

  for (const def of definitions) {
    try {
      // 检查是否已存在
      const existing = await db
        .select()
        .from(decorationDefinitions)
        .where((defs) => defs.imagePath === def.imagePath)
        .limit(1);

      if (existing.length > 0) {
        console.log(`⏭️  跳过已存在: ${def.name} (${def.imagePath})`);
        skipCount++;
        continue;
      }

      await db.insert(decorationDefinitions).values(def as any);
      console.log(`✅ 添加: ${def.name} - ${def.type} (${def.category})`);
      insertCount++;
    } catch (error) {
      console.error(`❌ 添加失败: ${def.name}`, error);
    }
  }

  console.log(`\n🎉 完成！`);
  console.log(`  ✅ 成功添加: ${insertCount} 个`);
  console.log(`  ⏭️  跳过重复: ${skipCount} 个`);
  console.log(`  📊 总计定义: ${definitions.length} 个`);
}

initDecorationDefinitions()
  .then(() => {
    console.log('\n✨ 初始化完成！');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ 错误:', error);
    process.exit(1);
  });
