/**
 * 初始化所有物品定义到items表
 * 包括：消耗品、装饰物、植物、建筑等
 */

import { db } from '../app/db';
import { items } from '../src/db/schema';

async function initItems() {
  console.log('🎨 开始初始化物品定义...\n');

  const itemsToInsert = [
    // ========================================
    // 消耗品 (原有的药品道具)
    // ========================================
    {
      itemId: 'small_stamina_pill',
      name: '小体力丸',
      nameEn: 'Small Stamina Pill',
      description: '恢复30点体力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'common',
      effects: { stamina: 30 },
      price: 50,
      sellPrice: 25,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_stamina_small.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'medium_stamina_pill',
      name: '中体力丸',
      nameEn: 'Medium Stamina Pill',
      description: '恢复60点体力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'uncommon',
      effects: { stamina: 60 },
      price: 100,
      sellPrice: 50,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_stamina_medium.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'large_stamina_pill',
      name: '大体力丸',
      nameEn: 'Large Stamina Pill',
      description: '恢复100点体力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'rare',
      effects: { stamina: 100 },
      price: 200,
      sellPrice: 100,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_stamina_large.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'small_qi_pill',
      name: '小内力丸',
      nameEn: 'Small Qi Pill',
      description: '恢复50点内力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'common',
      effects: { qi: 50 },
      price: 75,
      sellPrice: 37,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_qi_small.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'large_qi_pill',
      name: '大内力丸',
      nameEn: 'Large Qi Pill',
      description: '恢复100点内力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'rare',
      effects: { qi: 100 },
      price: 150,
      sellPrice: 75,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_qi_large.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'exp_scroll',
      name: '经验卷轴',
      nameEn: 'Experience Scroll',
      description: '获得1000点经验',
      itemType: 'consumable',
      category: 'scroll',
      rarity: 'rare',
      effects: { experience: 1000 },
      price: 500,
      sellPrice: 250,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/scroll_exp.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'black_go_stone',
      name: '黑色棋子',
      nameEn: 'Black Go Stone',
      description: '用于围棋对弈的黑子',
      itemType: 'material',
      category: 'go_material',
      rarity: 'common',
      price: 10,
      sellPrice: 5,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/icons/go_stone_black.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'white_go_stone',
      name: '白色棋子',
      nameEn: 'White Go Stone',
      description: '用于围棋对弈的白子',
      itemType: 'material',
      category: 'go_material',
      rarity: 'common',
      price: 10,
      sellPrice: 5,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/icons/go_stone_white.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'bamboo',
      name: '竹子',
      nameEn: 'Bamboo',
      description: '可以制作棋罐的竹子',
      itemType: 'material',
      category: 'crafting',
      rarity: 'common',
      prompt:
        'Bundle of fresh bamboo sticks, traditional Chinese crafting material, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 5,
      sellPrice: 2,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/isometric/plants/bamboo01.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'wood',
      name: '木材',
      nameEn: 'Wood',
      description: '可以制作棋盘的木材',
      itemType: 'material',
      category: 'crafting',
      rarity: 'common',
      prompt:
        'Stack of wooden planks, traditional woodworking material, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 5,
      sellPrice: 2,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/isometric/plants/bigtree01.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'stone',
      name: '石子',
      nameEn: 'Stone',
      description: '可以制作棋子的石子',
      itemType: 'material',
      category: 'crafting',
      rarity: 'common',
      prompt:
        'Pile of smooth river stones, crafting material for go stones, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 2,
      sellPrice: 1,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/isometric/items/rocks01.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'herb',
      name: '草药',
      nameEn: 'Herb',
      description: '用于制药的草药',
      itemType: 'material',
      category: 'crafting',
      rarity: 'common',
      prompt:
        'Bundle of medicinal herbs, traditional Chinese medicine ingredient, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 6,
      sellPrice: 2,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/icons/herb.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_bowl_1',
      name: '竹编棋罐',
      nameEn: 'Bamboo Go Bowl',
      description: '装备：最大体力 +8',
      descriptionEn: 'Equip: Max Stamina +8',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'common',
      effects: { maxStamina: 8 },
      prompt:
        'Traditional bamboo go bowl, woven texture, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 40,
      sellPrice: 15,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_bowl_1.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_bowl_2',
      name: '青竹棋罐',
      nameEn: 'Green Bamboo Go Bowl',
      description: '装备：最大体力 +12',
      descriptionEn: 'Equip: Max Stamina +12',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxStamina: 12 },
      prompt:
        'Green bamboo go bowl, polished bamboo texture, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 80,
      sellPrice: 30,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_bowl_2.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_bowl_3',
      name: '云纹棋罐',
      nameEn: 'Cloud-Pattern Go Bowl',
      description: '装备：最大体力 +16',
      descriptionEn: 'Equip: Max Stamina +16',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxStamina: 16 },
      prompt:
        'Go bowl with elegant cloud pattern engraving, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 140,
      sellPrice: 55,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_bowl.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_bowl_4',
      name: '玄玉棋罐',
      nameEn: 'Black Jade Go Bowl',
      description: '装备：最大体力 +22',
      descriptionEn: 'Equip: Max Stamina +22',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      effects: { maxStamina: 22 },
      prompt:
        'Black jade inlaid go bowl, luxurious yet traditional, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 220,
      sellPrice: 90,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_bowl_4.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_bowl_5',
      name: '天工棋罐',
      nameEn: 'Masterwork Go Bowl',
      description: '装备：最大体力 +30',
      descriptionEn: 'Equip: Max Stamina +30',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'epic',
      effects: { maxStamina: 30 },
      prompt:
        'Masterwork go bowl, exquisite craftsmanship, traditional Chinese style, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 360,
      sellPrice: 140,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_bowl_5.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_board_1',
      name: '松木棋盘',
      nameEn: 'Pine Go Board',
      description: '装备：最大内力 +8',
      descriptionEn: 'Equip: Max Qi +8',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'common',
      effects: { maxQi: 8 },
      prompt:
        'Traditional pine go board, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 60,
      sellPrice: 20,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_board_1.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_board_2',
      name: '竹纹棋盘',
      nameEn: 'Bamboo-Grain Go Board',
      description: '装备：最大内力 +12',
      descriptionEn: 'Equip: Max Qi +12',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxQi: 12 },
      prompt:
        'Go board with bamboo grain pattern, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 120,
      sellPrice: 45,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_board_2.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_board_3',
      name: '云纹棋盘',
      nameEn: 'Cloud-Pattern Go Board',
      description: '装备：最大内力 +16',
      descriptionEn: 'Equip: Max Qi +16',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxQi: 16 },
      prompt:
        'Go board with elegant cloud pattern engraving, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 180,
      sellPrice: 70,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_board_3.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_board_4',
      name: '金丝棋盘',
      nameEn: 'Gold-Inlaid Go Board',
      description: '装备：最大内力 +22',
      descriptionEn: 'Equip: Max Qi +22',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      effects: { maxQi: 22 },
      prompt:
        'Go board with gold inlay, luxurious yet traditional, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 280,
      sellPrice: 110,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_board_4.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'go_board_5',
      name: '天元棋盘',
      nameEn: 'Tengen Go Board',
      description: '装备：最大内力 +30',
      descriptionEn: 'Equip: Max Qi +30',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'epic',
      effects: { maxQi: 30 },
      prompt:
        'Masterwork go board symbolizing tengen, exquisite craftsmanship, clean game icon, top-down, isolated on transparent background, crisp edges, high detail',
      negativePrompt: 'text, watermark, logo, people, background, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      price: 420,
      sellPrice: 160,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/go_board_5.png',
      size: 1,
      blocking: false,
    },

    // ========================================
    // 棋谱/秘籍类道具
    // ========================================
    {
      itemId: 'qimen_dunjia',
      name: '奇门遁甲秘卷',
      nameEn: 'Qimen Dunjia Manual',
      description: '记载奇门遁甲阵法奥义的棋道秘卷',
      descriptionEn: 'A Go manual recording the secrets of Qimen Dunjia formations.',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      price: 0,
      sellPrice: 0,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/icons/scroll_exp.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'ouxue_poju',
      name: '呕血破局棋谱',
      nameEn: 'Blood-Vomiting Break Manual',
      description: '传说中以命破局的残谱，蕴含绝地求生之法',
      descriptionEn: 'A legendary Go manual of desperate breakthroughs, born of sacrifice.',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      price: 0,
      sellPrice: 0,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/icons/scroll_exp.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'sansheng_heyi',
      name: '三圣合一手札',
      nameEn: 'Three Saints Unity Notes',
      description: '琴棋剑三道合一的笔记，变化无穷',
      descriptionEn: 'Notes unifying Qin, Go, and Sword into a single principle.',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      price: 0,
      sellPrice: 0,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/icons/scroll_exp.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'yunv_xinjing',
      name: '玉女心经棋谱',
      nameEn: 'Jade Maiden Manual',
      description: '古墓棋局中流传的秘谱，清心守一',
      descriptionEn: 'A manual from the Ancient Tomb Go puzzle, emphasizing clarity and focus.',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      price: 0,
      sellPrice: 0,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/icons/scroll_exp.png',
      size: 1,
      blocking: false,
    },

    // ========================================
    // 室内装饰物 (indoor)
    // ========================================
    {
      itemId: 'chest01',
      name: '宝箱',
      description: '可以打开的宝箱，可能包含珍贵物品',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/chest01.png',
      size: 1,
      blocking: true,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'chest02',
      name: '宝箱',
      description: '可以打开的宝箱，可能包含珍贵物品',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/chest02.png',
      size: 1,
      blocking: true,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'boxes01',
      name: '箱子',
      description: '普通的储物箱',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/boxes01.png',
      size: 1,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'boxes02',
      name: '箱子',
      description: '普通的储物箱',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/boxes02.png',
      size: 1,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'mushroom01',
      name: '蘑菇',
      description: '可食用的蘑菇',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom01.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'mushroom02',
      name: '蘑菇',
      description: '可食用的蘑菇',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom02.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'rocks01',
      name: '岩石',
      description: '普通的岩石',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks01.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'rocks02',
      name: '岩石',
      description: '普通的岩石',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks02.png',
      size: 1,
      blocking: true,
    },

    // ========================================
    // 户外装饰物 (outdoor)
    // ========================================
    {
      itemId: 'carriage01',
      name: '马车',
      description: '装载货物的马车',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/carriage01.png',
      size: 2,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'rocks03',
      name: '岩石',
      description: '户外的大石头',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks03.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'rocks04',
      name: '岩石',
      description: '户外的大石头',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks04.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'rocks05',
      name: '岩石',
      description: '户外的大石头',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks05.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'mushroom03',
      name: '蘑菇',
      description: '野生蘑菇',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom03.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'mushroom04',
      name: '蘑菇',
      description: '野生蘑菇',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom04.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },

    // ========================================
    // 植物 (plants) - 每个文件都是独立的item
    // ========================================
    {
      itemId: 'bamboo01',
      name: '竹子',
      description: '可以制作棋罐的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo01.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bamboo02',
      name: '竹子',
      description: '可以制作棋罐的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo02.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bamboo03',
      name: '竹子',
      description: '可以制作棋罐的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo03.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bamboo04',
      name: '竹子',
      description: '可以制作棋罐的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo04.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bigtree01',
      name: '大树',
      description: '可以制作棋盘的大树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bigtree01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'bigtree02',
      name: '大树',
      description: '可以制作棋盘的大树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bigtree02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'bush01',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'bush02',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'bush03',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush03.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'bush04',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush04.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses01',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses01.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses02',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses02.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses03',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses03.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses04',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses04.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'palm01',
      name: '棕榈树',
      description: '热带植物，可以制作棋盘',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/palm01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'palm02',
      name: '棕榈树',
      description: '热带植物，可以制作棋盘',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/palm02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'pine_full01',
      name: '松树',
      description: '可以制作棋盘的松树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/pine-full01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'pine_full02',
      name: '松树',
      description: '可以制作棋盘的松树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/pine-full02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'shrub1_01',
      name: '灌木丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub1-01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'shrub1_02',
      name: '盆栽',
      description: '室内装饰植物',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub1-02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'shrub2_01',
      name: '灌木丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub2-01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'shrub2_02',
      name: '盆栽',
      description: '室内装饰植物',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub2-02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'tropical01',
      name: '热带植物',
      description: '可以制药的热带药草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/tropical01.png',
      size: 2,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'tropical02',
      name: '热带植物',
      description: '可以制药的热带药草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/tropical02.png',
      size: 2,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'weed01',
      name: '野草',
      description: '可以制药的野草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/weed01.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'weed02',
      name: '野草',
      description: '可以制药的野草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/weed02.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },

    // ========================================
    // 西式建筑 (buildings)
    // ========================================
    {
      itemId: 'church',
      name: '教堂',
      description: '大型教堂建筑，可进入触发剧情',
      itemType: 'building',
      category: 'buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/buildings/church/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'barracks',
      name: '兵营',
      description: '军队营地，可进入触发剧情',
      itemType: 'building',
      category: 'buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/buildings/barracks/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'firestation',
      name: '消防站',
      description: '消防站建筑，可进入触发剧情',
      itemType: 'building',
      category: 'buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/buildings/firestation/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'herbary',
      name: '草药铺',
      description: '草药店铺，可以购买药材和炼药',
      itemType: 'building',
      category: 'buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/buildings/herbary/renders/idle/45/000.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'weaponsmith',
      name: '武器铺',
      description: '武器店铺，可以购买和强化武器',
      itemType: 'building',
      category: 'buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/buildings/weaponsmith/renders/idle/45/000.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },

    // ========================================
    // 中式建筑 (chinese_buildings)
    // ========================================
    {
      itemId: 'small_2stories',
      name: '小型二层楼',
      description: '中式二层楼阁，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/small_2stories.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'altar',
      name: '祭坛',
      description: '祭祀用的祭坛，可以祈福',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/altar.png',
      size: 2,
      blocking: true,
      interactable: true,
      enterable: false,
    },
    {
      itemId: 'repair_building',
      name: '修缮建筑',
      description: '正在修缮的建筑',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/repair_building.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'stable',
      name: '马厩',
      description: '栓着的马匹，可以互动',
      itemType: 'decoration',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/stable.png',
      size: 2,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'house',
      name: '房屋',
      description: '普通民居，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/house.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'mechanic',
      name: '工坊',
      description: '工匠作坊，可以制作物品',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/mechanic.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'old_house',
      name: '老房子',
      description: '古老的房屋，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/old_house.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'palace',
      name: '宫殿',
      description: '宏伟的宫殿建筑，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/chinese_buildings/palace.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'platform',
      name: '平台',
      description: '石制平台',
      itemType: 'decoration',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/platform.png',
      size: 2,
      blocking: true,
      interactable: false,
    },
    {
      itemId: 'go_hall',
      name: '弈馆',
      description: '古时棋社集会之所，可切磋棋艺',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/go_hall.png',
      prompt:
        'Ancient Chinese Go hall, wooden building with hanging signboard, scholars playing Go inside, stone tables and Go boards, traditional tiled roof, elegant atmosphere, isometric view, game asset, plaque should say "奕馆", clean edges, standalone building on neutral background',
      negativePrompt:
        'modern, western, vehicles, people close-up, text, watermark, logo, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'go_pavilion',
      name: '弈亭',
      description: '石桌棋台，可练习手筋与打谱',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/go_pavilion.png',
      prompt:
        'Stone Go pavilion with a single stone table and Go board, small open-air pavilion or stone desk in a corner, traditional Chinese style, isometric view, game asset, clean edges, standalone object',
      negativePrompt:
        'modern, western, people close-up, text, watermark, logo, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 2,
      blocking: true,
      interactable: true,
      enterable: false,
    },
    {
      itemId: 'shop',
      name: '商铺',
      description: '商铺，可以购买物品',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/shop.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'hotel',
      name: '酒楼',
      description: '酒楼，可以休息和用餐',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/hotel.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'pharmacy',
      name: '药铺',
      description: '中药铺，可以购买药材和丹药',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/pharmacy.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'yard',
      name: '庭院',
      description: '庭院建筑，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/yard.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },

    // ========================================
    // 剧情宝物装备 (equipment)
    // ========================================
    {
      itemId: 'item_story_go_manual',
      name: '棋道手札',
      nameEn: 'Go Notes',
      description: '装备：最大内力 +15',
      descriptionEn: 'Equip: Max Qi +15',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxQi: 15 },
      price: 200,
      sellPrice: 80,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_go_manual.png',
      prompt:
        'Ancient stitched booklet for Go study, jade clasp, elegant Chinese style, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_talisman',
      name: '山行护符',
      nameEn: 'Mountain Talisman',
      description: '装备：最大体力 +15',
      descriptionEn: 'Equip: Max Stamina +15',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxStamina: 15 },
      price: 200,
      sellPrice: 80,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_talisman.png',
      prompt:
        'Traditional Chinese talisman charm, red and gold thread, small jade pendant, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_pine_tea',
      name: '松针清茶',
      nameEn: 'Pine Needle Tea',
      description: '装备：最大内力 +8',
      descriptionEn: 'Equip: Max Qi +8',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'common',
      effects: { maxQi: 8 },
      price: 120,
      sellPrice: 40,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_pine_tea.png',
      prompt:
        'Small tea bundle wrapped in paper, pine needle tea, bamboo string, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_monk_blessing',
      name: '禅定香囊',
      nameEn: 'Meditation Sachet',
      description: '装备：最大内力 +20',
      descriptionEn: 'Equip: Max Qi +20',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      effects: { maxQi: 20 },
      price: 260,
      sellPrice: 100,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_monk_blessing.png',
      prompt:
        'Buddhist meditation sachet, saffron pouch with silk cord, subtle incense glow, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_iron_staff_token',
      name: '铁杖印记',
      nameEn: 'Iron Staff Mark',
      description: '装备：最大体力 +20',
      descriptionEn: 'Equip: Max Stamina +20',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      effects: { maxStamina: 20 },
      price: 260,
      sellPrice: 100,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_iron_staff_token.png',
      prompt:
        'Iron staff token medallion, dark metal with etched pattern, rugged wuxia style, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_weighted_stone',
      name: '定手石',
      nameEn: 'Steadying Stone',
      description: '装备：最大体力 +10',
      descriptionEn: 'Equip: Max Stamina +10',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxStamina: 10 },
      price: 180,
      sellPrice: 70,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_weighted_stone.png',
      prompt:
        'Smooth weighted training stone, dark slate color, subtle carving, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_scatter_pouch',
      name: '散势袋',
      nameEn: 'Scattering Pouch',
      description: '装备：最大内力 +10',
      descriptionEn: 'Equip: Max Qi +10',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxQi: 10 },
      price: 180,
      sellPrice: 70,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_scatter_pouch.png',
      prompt:
        'Small cloth pouch with scattered stones inside, tied with cord, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_calm_chord',
      name: '清弦谱',
      nameEn: 'Calming Chord',
      description: '装备：最大内力 +25',
      descriptionEn: 'Equip: Max Qi +25',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      effects: { maxQi: 25 },
      price: 320,
      sellPrice: 120,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_calm_chord.png',
      prompt:
        'Ancient qin music sheet, silk scroll with string motif, elegant and calm, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_edge_charm',
      name: '决断符',
      nameEn: 'Decisive Charm',
      description: '装备：最大体力 +25',
      descriptionEn: 'Equip: Max Stamina +25',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'rare',
      effects: { maxStamina: 25 },
      price: 320,
      sellPrice: 120,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_edge_charm.png',
      prompt:
        'Wuxia talisman of resolve, sharp-edged charm with metallic sheen, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_blood_manual',
      name: '呕血谱拓本',
      nameEn: 'Manual Rubbing',
      description: '装备：最大内力 +12',
      descriptionEn: 'Equip: Max Qi +12',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxQi: 12 },
      price: 220,
      sellPrice: 90,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_blood_manual.png',
      prompt:
        'Rubbing of an ancient Go manual, inked paper with seal, rolled edges, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_inkstone',
      name: '静心墨石',
      nameEn: 'Calm Inkstone',
      description: '装备：最大内力 +10',
      descriptionEn: 'Equip: Max Qi +10',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'common',
      effects: { maxQi: 10 },
      price: 160,
      sellPrice: 60,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_inkstone.png',
      prompt:
        'Elegant inkstone with ink stick, scholar tools, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_clear_mind',
      name: '清心丸',
      nameEn: 'Clear Mind Pill',
      description: '装备：最大内力 +18',
      descriptionEn: 'Equip: Max Qi +18',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxQi: 18 },
      price: 240,
      sellPrice: 95,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_clear_mind.png',
      prompt:
        'Small jade pill bottle with a single luminous pill, calming aura, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },
    {
      itemId: 'item_story_zhenlong_notes',
      name: '珍珑札记',
      nameEn: 'Zhenlong Notes',
      description: '装备：最大体力 +18',
      descriptionEn: 'Equip: Max Stamina +18',
      itemType: 'equipment',
      category: 'treasure',
      rarity: 'uncommon',
      effects: { maxStamina: 18 },
      price: 240,
      sellPrice: 95,
      stackable: false,
      maxStack: 1,
      imagePath: '/game/generated/equipments/item_story_zhenlong_notes.png',
      prompt:
        'Zhenlong puzzle notes, folded paper with binding cord, elegant scholar style, game item icon, top-down isometric, clean background, high detail, no text',
      negativePrompt: 'text, watermark, logo, people, blurry, low quality',
      imageWidth: 512,
      imageHeight: 512,
      size: 1,
      blocking: false,
    },

    // ========================================
    // 动画装饰物 (animated)
    // ========================================
    {
      itemId: 'signal_fire',
      name: '信号火',
      description: '燃烧的信号火',
      itemType: 'decoration',
      category: 'animated',
      rarity: 'uncommon',
      imagePath: '/game/isometric/buildings/signal_fire/renders/work/45/000.png',
      size: 2,
      blocking: true,
      interactable: false,
      animated: true,
      animationPath: '/game/isometric/buildings/signal_fire/renders/work/45',
      frameCount: 16,
    },
  ];

  // 批量插入
  let insertCount = 0;
  let skipCount = 0;

  for (const item of itemsToInsert) {
    try {
      // 检查是否已存在（使用eq比较器）
      const { eq } = await import('drizzle-orm');
      const existing = await db.select().from(items).where(eq(items.itemId, item.itemId)).limit(1);

      if (existing.length > 0) {
        console.log(`⏭️  跳过已存在: ${item.name} (${item.itemId})`);
        skipCount++;
        continue;
      }

      await db.insert(items).values(item as any);
      console.log(`✅ 添加: ${item.name} [${item.itemType}] - ${item.itemId}`);
      insertCount++;
    } catch (error) {
      console.error(`❌ 添加失败: ${item.name}`, error);
    }
  }

  console.log(`\n🎉 完成！`);
  console.log(`  ✅ 成功添加: ${insertCount} 个`);
  console.log(`  ⏭️  跳过重复: ${skipCount} 个`);
  console.log(`  📊 总计定义: ${itemsToInsert.length} 个`);
  console.log(`\n📊 分类统计:`);
  console.log(`  💊 消耗品: ${itemsToInsert.filter((i) => i.itemType === 'consumable').length} 个`);
  console.log(`  🎨 装饰物: ${itemsToInsert.filter((i) => i.itemType === 'decoration').length} 个`);
  console.log(`  🌿 植物: ${itemsToInsert.filter((i) => i.itemType === 'plant').length} 个`);
  console.log(`  🏛️  建筑: ${itemsToInsert.filter((i) => i.itemType === 'building').length} 个`);
  console.log(`  📦 材料: ${itemsToInsert.filter((i) => i.itemType === 'material').length} 个`);
  console.log(`  🧿 装备: ${itemsToInsert.filter((i) => i.itemType === 'equipment').length} 个`);
}

initItems()
  .then(() => {
    console.log('\n✨ 初始化完成！');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ 错误:', error);
    process.exit(1);
  });
