/**
 * 初始化所有物品定义到items表
 * 包括：消耗品、装饰物、植物、建筑等
 */

import { db } from '../app/db';
import { items } from '../src/db/schema';

async function initItems() {
  console.log('🎨 开始初始化物品定义...\n');

  const itemsToInsert = [
    // ========================================
    // 消耗品 (原有的药品道具)
    // ========================================
    {
      itemId: 'small_stamina_pill',
      name: '小体力丸',
      nameEn: 'Small Stamina Pill',
      description: '恢复30点体力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'common',
      effects: { stamina: 30 },
      price: 50,
      sellPrice: 25,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_stamina_small.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'medium_stamina_pill',
      name: '中体力丸',
      nameEn: 'Medium Stamina Pill',
      description: '恢复60点体力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'uncommon',
      effects: { stamina: 60 },
      price: 100,
      sellPrice: 50,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_stamina_medium.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'large_stamina_pill',
      name: '大体力丸',
      nameEn: 'Large Stamina Pill',
      description: '恢复100点体力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'rare',
      effects: { stamina: 100 },
      price: 200,
      sellPrice: 100,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_stamina_large.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'small_qi_pill',
      name: '小内力丸',
      nameEn: 'Small Qi Pill',
      description: '恢复50点内力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'common',
      effects: { qi: 50 },
      price: 75,
      sellPrice: 37,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_qi_small.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'large_qi_pill',
      name: '大内力丸',
      nameEn: 'Large Qi Pill',
      description: '恢复100点内力',
      itemType: 'consumable',
      category: 'potion',
      rarity: 'rare',
      effects: { qi: 100 },
      price: 150,
      sellPrice: 75,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/potion_qi_large.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'exp_scroll',
      name: '经验卷轴',
      nameEn: 'Experience Scroll',
      description: '获得200点经验',
      itemType: 'consumable',
      category: 'scroll',
      rarity: 'rare',
      effects: { experience: 200 },
      price: 500,
      sellPrice: 250,
      stackable: true,
      maxStack: 99,
      imagePath: '/game/icons/scroll_exp.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'black_go_stone',
      name: '黑色棋子',
      nameEn: 'Black Go Stone',
      description: '用于围棋对弈的黑子',
      itemType: 'material',
      category: 'go_material',
      rarity: 'common',
      price: 10,
      sellPrice: 5,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/icons/go_stone_black.png',
      size: 1,
      blocking: false,
    },
    {
      itemId: 'white_go_stone',
      name: '白色棋子',
      nameEn: 'White Go Stone',
      description: '用于围棋对弈的白子',
      itemType: 'material',
      category: 'go_material',
      rarity: 'common',
      price: 10,
      sellPrice: 5,
      stackable: true,
      maxStack: 999,
      imagePath: '/game/icons/go_stone_white.png',
      size: 1,
      blocking: false,
    },

    // ========================================
    // 室内装饰物 (indoor)
    // ========================================
    {
      itemId: 'chest01',
      name: '宝箱',
      description: '可以打开的宝箱，可能包含珍贵物品',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/chest01.png',
      size: 1,
      blocking: true,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'chest02',
      name: '宝箱',
      description: '可以打开的宝箱，可能包含珍贵物品',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/chest02.png',
      size: 1,
      blocking: true,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'boxes01',
      name: '箱子',
      description: '普通的储物箱',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/boxes01.png',
      size: 1,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'boxes02',
      name: '箱子',
      description: '普通的储物箱',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/boxes02.png',
      size: 1,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'mushroom01',
      name: '蘑菇',
      description: '可食用的蘑菇',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom01.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'mushroom02',
      name: '蘑菇',
      description: '可食用的蘑菇',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom02.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'rocks01',
      name: '岩石',
      description: '普通的岩石',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks01.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'rocks02',
      name: '岩石',
      description: '普通的岩石',
      itemType: 'decoration',
      category: 'indoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks02.png',
      size: 1,
      blocking: true,
    },

    // ========================================
    // 户外装饰物 (outdoor)
    // ========================================
    {
      itemId: 'carriage01',
      name: '马车',
      description: '装载货物的马车',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/carriage01.png',
      size: 2,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'rocks03',
      name: '岩石',
      description: '户外的大石头',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks03.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'rocks04',
      name: '岩石',
      description: '户外的大石头',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks04.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'rocks05',
      name: '岩石',
      description: '户外的大石头',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/rocks05.png',
      size: 1,
      blocking: true,
    },
    {
      itemId: 'mushroom03',
      name: '蘑菇',
      description: '野生蘑菇',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom03.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },
    {
      itemId: 'mushroom04',
      name: '蘑菇',
      description: '野生蘑菇',
      itemType: 'decoration',
      category: 'outdoor',
      rarity: 'common',
      imagePath: '/game/isometric/items/mushroom04.png',
      size: 1,
      blocking: false,
      interactable: true,
      pickable: true,
    },

    // ========================================
    // 植物 (plants) - 每个文件都是独立的item
    // ========================================
    {
      itemId: 'bamboo01',
      name: '竹子',
      description: '可以制作棋盘的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo01.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bamboo02',
      name: '竹子',
      description: '可以制作棋盘的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo02.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bamboo03',
      name: '竹子',
      description: '可以制作棋盘的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo03.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bamboo04',
      name: '竹子',
      description: '可以制作棋盘的竹子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bamboo04.png',
      size: 1,
      blocking: true,
      plantType: 'bamboo',
      harvestable: true,
    },
    {
      itemId: 'bigtree01',
      name: '大树',
      description: '可以制作棋盘和棋子的大树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bigtree01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'bigtree02',
      name: '大树',
      description: '可以制作棋盘和棋子的大树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bigtree02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'bush01',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'bush02',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'bush03',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush03.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'bush04',
      name: '灌木',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/bush04.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses01',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses01.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses02',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses02.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses03',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses03.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'grasses04',
      name: '草丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/grasses04.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'palm01',
      name: '棕榈树',
      description: '热带植物，可以制作棋盘和棋子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/palm01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'palm02',
      name: '棕榈树',
      description: '热带植物，可以制作棋盘和棋子',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/palm02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'pine_full01',
      name: '松树',
      description: '可以制作棋盘和棋子的松树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/pine-full01.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'pine_full02',
      name: '松树',
      description: '可以制作棋盘和棋子的松树',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/pine-full02.png',
      size: 2,
      blocking: true,
      plantType: 'tree',
      harvestable: true,
    },
    {
      itemId: 'shrub1_01',
      name: '灌木丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub1-01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'shrub1_02',
      name: '盆栽',
      description: '室内装饰植物',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub1-02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: false,
    },
    {
      itemId: 'shrub2_01',
      name: '灌木丛',
      description: '可以制药的草药',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub2-01.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'shrub2_02',
      name: '盆栽',
      description: '室内装饰植物',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/shrub2-02.png',
      size: 1,
      blocking: true,
      plantType: 'herb',
      harvestable: false,
    },
    {
      itemId: 'tropical01',
      name: '热带植物',
      description: '可以制药的热带药草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/tropical01.png',
      size: 2,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'tropical02',
      name: '热带植物',
      description: '可以制药的热带药草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/tropical02.png',
      size: 2,
      blocking: true,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'weed01',
      name: '野草',
      description: '可以制药的野草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/weed01.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },
    {
      itemId: 'weed02',
      name: '野草',
      description: '可以制药的野草',
      itemType: 'plant',
      category: 'plants',
      rarity: 'common',
      imagePath: '/game/isometric/plants/weed02.png',
      size: 1,
      blocking: false,
      plantType: 'herb',
      harvestable: true,
    },

    // ========================================
    // 西式建筑 (buildings)
    // ========================================
    {
      itemId: 'church',
      name: '教堂',
      description: '大型教堂建筑，可进入触发剧情',
      itemType: 'building',
      category: 'buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/buildings/church/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'barracks',
      name: '兵营',
      description: '军队营地，可进入触发剧情',
      itemType: 'building',
      category: 'buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/buildings/barracks/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'firestation',
      name: '消防站',
      description: '消防站建筑，可进入触发剧情',
      itemType: 'building',
      category: 'buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/buildings/firestation/renders/idle/45/000.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'herbary',
      name: '草药铺',
      description: '草药店铺，可以购买药材和炼药',
      itemType: 'building',
      category: 'buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/buildings/herbary/renders/idle/45/000.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'weaponsmith',
      name: '武器铺',
      description: '武器店铺，可以购买和强化武器',
      itemType: 'building',
      category: 'buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/buildings/weaponsmith/renders/idle/45/000.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },

    // ========================================
    // 中式建筑 (chinese_buildings)
    // ========================================
    {
      itemId: 'small_2stories',
      name: '小型二层楼',
      description: '中式二层楼阁，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/small_2stories.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'altar',
      name: '祭坛',
      description: '祭祀用的祭坛，可以祈福',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/altar.png',
      size: 2,
      blocking: true,
      interactable: true,
      enterable: false,
    },
    {
      itemId: 'repair_building',
      name: '修缮建筑',
      description: '正在修缮的建筑',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/repair_building.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'stable',
      name: '马厩',
      description: '栓着的马匹，可以互动',
      itemType: 'decoration',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/stable.png',
      size: 2,
      blocking: true,
      interactable: true,
    },
    {
      itemId: 'house',
      name: '房屋',
      description: '普通民居，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/house.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'mechanic',
      name: '工坊',
      description: '工匠作坊，可以制作物品',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/mechanic.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'old_house',
      name: '老房子',
      description: '古老的房屋，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/old_house.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'palace',
      name: '宫殿',
      description: '宏伟的宫殿建筑，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'rare',
      imagePath: '/game/isometric/chinese_buildings/palace.png',
      size: 4,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'platform',
      name: '平台',
      description: '石制平台',
      itemType: 'decoration',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/platform.png',
      size: 2,
      blocking: true,
      interactable: false,
    },
    {
      itemId: 'shop',
      name: '商铺',
      description: '商铺，可以购买物品',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/shop.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'hotel',
      name: '酒楼',
      description: '酒楼，可以休息和用餐',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/hotel.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'pharmacy',
      name: '药铺',
      description: '中药铺，可以购买药材和丹药',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'uncommon',
      imagePath: '/game/isometric/chinese_buildings/pharmacy.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },
    {
      itemId: 'yard',
      name: '庭院',
      description: '庭院建筑，可进入触发剧情',
      itemType: 'building',
      category: 'chinese_buildings',
      rarity: 'common',
      imagePath: '/game/isometric/chinese_buildings/yard.png',
      size: 3,
      blocking: true,
      interactable: true,
      enterable: true,
    },

    // ========================================
    // 动画装饰物 (animated)
    // ========================================
    {
      itemId: 'signal_fire',
      name: '信号火',
      description: '燃烧的信号火',
      itemType: 'decoration',
      category: 'animated',
      rarity: 'uncommon',
      imagePath: '/game/isometric/buildings/signal_fire/renders/work/45/000.png',
      size: 2,
      blocking: true,
      interactable: false,
      animated: true,
      animationPath: '/game/isometric/buildings/signal_fire/renders/work/45',
      frameCount: 16,
    },
  ];

  // 批量插入
  let insertCount = 0;
  let skipCount = 0;

  for (const item of itemsToInsert) {
    try {
      // 检查是否已存在（使用eq比较器）
      const {eq} = await import('drizzle-orm');
      const existing = await db
        .select()
        .from(items)
        .where(eq(items.itemId, item.itemId))
        .limit(1);

      if (existing.length > 0) {
        console.log(`⏭️  跳过已存在: ${item.name} (${item.itemId})`);
        skipCount++;
        continue;
      }

      await db.insert(items).values(item as any);
      console.log(`✅ 添加: ${item.name} [${item.itemType}] - ${item.itemId}`);
      insertCount++;
    } catch (error) {
      console.error(`❌ 添加失败: ${item.name}`, error);
    }
  }

  console.log(`\n🎉 完成！`);
  console.log(`  ✅ 成功添加: ${insertCount} 个`);
  console.log(`  ⏭️  跳过重复: ${skipCount} 个`);
  console.log(`  📊 总计定义: ${itemsToInsert.length} 个`);
  console.log(`\n📊 分类统计:`);
  console.log(`  💊 消耗品: ${itemsToInsert.filter(i => i.itemType === 'consumable').length} 个`);
  console.log(`  🎨 装饰物: ${itemsToInsert.filter(i => i.itemType === 'decoration').length} 个`);
  console.log(`  🌿 植物: ${itemsToInsert.filter(i => i.itemType === 'plant').length} 个`);
  console.log(`  🏛️  建筑: ${itemsToInsert.filter(i => i.itemType === 'building').length} 个`);
  console.log(`  📦 材料: ${itemsToInsert.filter(i => i.itemType === 'material').length} 个`);
}

initItems()
  .then(() => {
    console.log('\n✨ 初始化完成！');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ 错误:', error);
    process.exit(1);
  });
